### ISSUE TITLE
ProtonVPN on F-Droid was crash

### ISSUE THREAD

**Issue by nuit7712** [ProtonVPN/android-app#31] opened 2020-06-02 12:28 UTC
ProtonVPN installed from F-Droid was crash.
(not even open)

(Version 2.2.2 added on 2020/6/2)

**Comment by yyhmsg** [comment] 2020-06-02 13:17
I've experienced this as well.  The app crashes at start and no rebooting or cache clearing helps.

**Comment by nuit7712** [comment] 2020-06-02 13:24
I clear catch and rdboot my device too.
I even delete and reinstall it.

**Comment by AlgirdasPundzius** [comment] 2020-06-02 13:27
Duplicate of https://github.com/ProtonVPN/android-app/issues/23

For now please continue to use 2.1.7, until 2.2.3 version is available on F-droid. Sorry for inconvenience

**Closed by AlgirdasPundzius** 2020-06-02 13:27 UTC
