### ISSUE TITLE
Crash in Android 10

### ISSUE THREAD

**Issue by stevenleeS0ht** [ProtonVPN/android-app#26] opened 2020-05-08 08:47 UTC
I install this app on both of my Android 10 devices. But when I launch the app on these devices, both of ProtonVPN crashed.

I think there is still some works to do on the compatibility of ProtonVPN on Android 10.

**Comment by AlgirdasPundzius** [comment] 2020-05-08 09:18
Hello, 
Are you installing app from some store or are building it yourself (if so could you provide a stacktrace)? Also, what kind of devices exactly ?

**Comment by dnylo** [comment] 2020-05-08 12:02
I have the same problem on Android 9 and 10 with the F-Droid build (2.1.3.20103): ProtonVPN crashes on opening the app (sometimes I get a white screen for less than a second and then the OS asks me to wait or to close the app).
There is no problem with the Play Store version (2.1.5.20020105).

My Android 9 device is a OnePlus 2 (ONE A2003, LineageOS 16.0 18/04/2020 build).
My Android 10 device is a OnePlus 7T (HD1903, Oxygen OS 10.0.9.HD65BA).

**Comment by AlgirdasPundzius** [comment] 2020-05-08 12:59
Yes, the issue is resolved with 2.1.7 version. Hopefully it reaches F-droid soon

**Closed by AlgirdasPundzius** 2020-05-08 12:59 UTC
